config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "welcome#index"
  resources :contact_form, only: %i[new create]
  # resources :users, only: %i[new create]
  
  resources :users, only: [:edit, :update, :destroy] do
    resources :settings, only: [:index]
  end
  
  get "dashboard/:id", to: "users#show", as: :dashboard
  # get "register", to: "registrations#new"
  # post "register", to: "registrations#create"
  get "leadership", to: "employees#index"
  # get "login", to: "logins#new"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  

  def new
    
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      #Send Email
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    flash[:notice] = "If an account with that email was found, we have sent a link to reset your password"
    redirect_to new_session_path
  end

  def edit
    # require 'pry'; binding.pry
    @user = User.find_signed(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      flash[:alert] = "Your token has expired, please try again."
      redirect_to new_session_path
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")

    if @user.update(password_params)
      flash[:notice] = "Your password was reset successfully. Please sign in."
      redirect_to new_session_path
    else
      flash.now[:alert] = @user.errors.full_messages.uniq.to_sentence
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1 class="display-5 subheader">Reset your password</h1>
</div>
<hr>

<div class="container">
  <%= form_with model: @user, url: password_reset_edit_path( token: params[:token]), local: true, data: { turbo: false}, class: "container" do |form| %>

    <div class="mb-3">
    <%= form.label :password, class: "required text-muted" %>
    <%= form.password_field :password, class: "form-control", required: true, placeholder: "Password" %>
    </div>

    <div class="mb-3">
    <%= form.label :password_confirmation, class: "required text-muted" %>
    <%= form.password_field :password_confirmation, class: "form-control", required: true, placeholder: "Password" %>
    </div>

    <div class="mb-3">
      <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>

    <div class="mb-3"><%= link_to "Forgot your password?", new_password_reset_path %></div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1 class="display-5 subheader">Forgot Password?</h1>
</div>
<hr>

<div class="container">
  <%= form_with url: password_reset_path, local: true, data: { turbo: false}, class: "container" do |form| %>

    <div class="mb-3">
    <%= form.label :email, class: "required text-muted" %>
    <%= form.text_field :email, class: "form-control", required: true, placeholder: "user@email.com" %>
  </div>

    <div class="mb-3">
      <%= form.submit "Reset Password", class: "btn btn-primary" %>
      </div>
      <div class="mb-1"><%= link_to "New User? Sign Up Here!", new_registration_path %></div>

    
    <% end %>
</div>