config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "welcome#index"
  resources :contact_form, only: %i[new create]
  # resources :users, only: %i[new create]
  
  resources :users, only: [:edit, :update, :destroy] do
    resources :settings, only: [:index]
  end
  
  get "dashboard/:id", to: "users#show", as: :dashboard
  # get "register", to: "registrations#new"
  # post "register", to: "registrations#create"
  get "leadership", to: "employees#index"
  # get "login", to: "logins#new"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
  def create
    @name = params[:contact_form][:name]
    @email = params[:contact_form][:email]
    @message = params[:contact_form][:message]

    NotifierMailer.simple_message(@name, @email, @message).deliver_later
    NotifierMailer.contact_form_receipt(@name, @email).deliver_later
    flash[:notice] = "Your message has been sent successfully."
    redirect_to :new_contact_form
  end

end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/views/contact_form/new.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1 class="display-5 subheader">Get In Touch</h1>
</div>

<hr>

<div class="d-flex align-items-center justify-content-center mt-2">
  <h4 class="mt-3 text-muted">You may reach us at <%= link_to "(346) 554-3706", "tel:346-554-3706" %>, or through the contact form below:</h4>
</div>
<div class="container mt-2">
  <%= form_with scope: :contact_form, url: contact_form_index_path, method: :post, local: true, class: "container" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "required text-muted" %>
      <%= form.text_field :name, class: "form-control", required: true, placeholder: "Name" %>
    </div>
    <div class="mb-3">
      <%= form.label :email, class: "required text-muted" %>
      <%= form.email_field :email, class: "form-control", required: true, placeholder: "Email" %>
    </div>
    <div class="mb-3">
      <%= form.label :message, class: "required text-muted" %>
      <%= form.text_area :message, class: "form-control", required: true, placeholder: "Please provide general details of your valuation needs, including proposal purpose (potential sale, internal planning or other) and best method of contact." %>
    </div>
    <div class="mb-3">
      <%= form.submit "Send", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>