config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "welcome#index"
  resources :contact_form, only: %i[new create]
  # resources :users, only: %i[new create]
  
  resources :users, only: [:edit, :update, :destroy] do
    resources :settings, only: [:index]
  end
  
  get "dashboard/:id", to: "users#show", as: :dashboard
  # get "register", to: "registrations#new"
  # post "register", to: "registrations#create"
  get "leadership", to: "employees#index"
  # get "login", to: "logins#new"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="">
  <h3><strong class="footer-strong">Insight Valuations, LLC</strong></h3>
  <h3>We Can Value That&#8482</h3>
  <h3>Houston, Texas</h3>
  <p class="text-muted">Copyright &copy 2023 Insight Valuations, LLC - All Rights Reserved.</p>
  <p class="text-muted">
    This site is <strong>SOON</strong> to be protected by reCAPTCHA and both the
    <%= link_to "Google Privacy Policy", "https://policies.google.com/privacy" %>
    and <%= link_to "Terms of Service", "https://policies.google.com/terms" %>
    will apply.
  </p>
</footer>

app/views/shared/_header.html.erb
<header>
<div class="d-flex align-items-center justify-content-center">
  <div><%= image_tag 'iv_logo.jpg', class: "img-fluid logo-img" %></div>
</div>
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-light navbar-light fixed-top navbar-scroll translucent-navbar" data-mdb-navbar-init>
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand navbar-start-margin " %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <!--
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        -->
        <li class="nav-item">
          <%= link_to "Leadership", leadership_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", new_contact_form_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link" %>
        </li>
        <% end %>

        <li class="nav-item">
          <a href="tel:346-554-3706" class="nav-link">
            <i class="fas fa-phone"></i>
          </a>
        </li>

        <li class="nav-item">
          <a href="mailto:matthewwmjohnson@gmail.com" class="nav-link">
            <i class="far fa-envelope"></i>
          </a>
        </li>
        

        <!-- 
        <li class="nav-item">
          <%= link_to "Sign Up", new_registration_path, class: "nav-link" %>
        </li>
        -->
        <!--
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> 
        -->
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <!-- 
        <li class="nav-item">
          <%= link_to "Register", new_registration_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Login", session_path, class: "btn btn-primary btn-md mt-0" %>
        </li>
        -->

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Settings", user_settings_path(current_user), method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Log out", session_path, method: :delete, class: "btn btn-primary btn-md mt-0 right-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Register", new_registration_path, method: :get, class: "nav-link" %>
          </li>
            <li class="nav-item">
            <%= link_to "Login", new_session_path, method: :get, class: "btn btn-primary btn-md mt-0 right-link" %>
          </li>
        <% end %>

      
      </ul>
    </div>
  </div>
</nav>