config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "welcome#index"
  resources :contact_form, only: %i[new create]
  # resources :users, only: %i[new create]
  
  resources :users, only: [:edit, :update, :destroy] do
    resources :settings, only: [:index]
  end
  
  get "dashboard/:id", to: "users#show", as: :dashboard
  # get "register", to: "registrations#new"
  # post "register", to: "registrations#create"
  get "leadership", to: "employees#index"
  # get "login", to: "logins#new"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!


  def index
    @user = current_user
  end
end

app/views/settings/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1 class="display-5 subheader"> Settings</h1>
</div>
<hr>

<div class="container-flex align-items-center justify-content-center">
    <ul class="no-list-style">
      <li><%= link_to "Edit Profile", edit_user_path(@user) %></li>
      <li><%= link_to "Change Password", edit_password_path %></li>
      <li><%= link_to "Delete Account", user_path(current_user), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete your account? This cannot be undone." } %></li>
    </ul>
</div>